/auth/local:
  x-swagger-router-controller: local
# Passport
  post:
    operationId: callback
    tags:
      - Login
    summary: Login
    description: Default [ admin/123 ] - [ user/123 ]
    parameters:
      - name: username
        in: query
        description: Username...
        required: true
        type: string
      - name: password
        in: query
        description: Password...
        required: true
        type: string
        format: password
    responses:
      200:
        description: Success
      422:
        description: Login Invalid
      500:
        description: Error
