/auth/local:
  x-swagger-router-controller: local
# callback
  post:
    operationId: callback
    tags:
      - Authentication
    summary: Signin
    description: Login --> admin - 123 / user - 123
    consumes:
      - application/x-www-form-urlencoded
    parameters:
      - name: username
        in: formData
        description: Username...
        required: true
        type: string
      - name: password
        in: formData
        description: Password...
        required: true
        type: string
        format: password
    responses:
      200:
        description: Success
      422:
        description: Login Invalid
      500:
        description: Error