/auth/twitter:
  x-swagger-router-controller: twitter
# index
  get:
    operationId: index
    x-hide: true
    tags:
      - Social
    summary: Authenticate with Twitter
    description: Authenticate with Twitter
    responses:
      200:
        $ref: '#/responses/auth-200'
      422:
        $ref: '#/responses/auth-422'
      500:
        $ref: '#/responses/auth-500'

/auth/twitter/callback:
  x-swagger-router-controller: twitter
# callback
  get:
    operationId: callback
    x-hide: true
    tags:
      - Social
    summary: Callback with Twitter
    description: Callback with Twitter
    responses:
      200:
        $ref: '#/responses/auth-200'
      422:
        $ref: '#/responses/auth-422'
      500:
        $ref: '#/responses/auth-500'

        