/auth/local:
  # Passport
  post:
    x-swagger-router-controller: 'login.controller'
    tags:
      - "Login"
    summary: "Logs user into the system"
    description: "Login user"
    operationId: "login"
    parameters:
      - name: "username"
        in: "query"
        description: "The username for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
    responses:
      200:
        description: "successful operation"
      400:
        description: "Login Invalid"
      500:
        description: "Error"
